FROM ubuntu:18.04
RUN  apt update 
RUN  apt install git  openssh-client ca-certificates -y
COPY ./bin/webhooks  /webhooks
RUN mkdir -p /jxhome
ENV JX_HOME /jxhome
ENV PATH /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
ENTRYPOINT ["/webhooks"]
