FROM ubuntu:18.04
RUN  apt update 
RUN  apt install dialog
RUN  apt install -y  git  openssh-client ca-certificates 
RUN  git version
RUN which git 
COPY ./bin/webhooks  /webhooks
RUN mkdir -p /jxhome
ENV JX_HOME /jxhome
ENV PATH /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
RUN ls /usr/bin
RUN cp /usr/bin/git /
ENTRYPOINT ["/webhooks"]
